# Render deployment configuration for InterviewPilot
services:
  - type: web
    name: interviewpilot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: RENDER
        value: true  # Flag to identify Render environment
      - key: MONGODB_URL
        sync: false  # Set manually in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_NAME
        value: interviewpilot
      - key: ALLOWED_ORIGINS
        value: "*"  # Update this after deploying frontend
